// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIxfOvWUZYsFiEe7ACp29g_UoypChJvJg',
    appId: '1:201202530490:ios:68a5488e5c2a4f7894ea83',
    messagingSenderId: '201202530490',
    projectId: 'team-capstone-design',
    storageBucket: 'team-capstone-design.firebasestorage.app',
    iosBundleId: 'com.example.team4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeHfHRHRTvBRcBLD2u8JByUJJLk_wl770',
    appId: '1:201202530490:web:f2010319553df2e394ea83',
    messagingSenderId: '201202530490',
    projectId: 'team-capstone-design',
    authDomain: 'team-capstone-design.firebaseapp.com',
    storageBucket: 'team-capstone-design.firebasestorage.app',
    measurementId: 'G-YPBM0TN9MV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3egeS34dwN6E8WcSyeTq7-byDu5UR-_4',
    appId: '1:201202530490:android:abb4b10ca9bb1cb894ea83',
    messagingSenderId: '201202530490',
    projectId: 'team-capstone-design',
    storageBucket: 'team-capstone-design.firebasestorage.app',
  );

}