// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmoW3f1oMVFc5qbJrkxEQuwUxPzGzPL6o',
    appId: '1:269398467482:ios:d02970ee748bad55c15023',
    messagingSenderId: '269398467482',
    projectId: 'team4-2252f',
    storageBucket: 'team4-2252f.firebasestorage.app',
    iosBundleId: 'com.example.team4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCebyu6dhcfOMNQbRP4Nahv2DIMHR0C8Q',
    appId: '1:269398467482:web:29c36437e5e27b8dc15023',
    messagingSenderId: '269398467482',
    projectId: 'team4-2252f',
    authDomain: 'team4-2252f.firebaseapp.com',
    storageBucket: 'team4-2252f.firebasestorage.app',
    measurementId: 'G-H0S558MH69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOUnJ6X-KKmEaHJDmq3GN3UKaOg0xwg3g',
    appId: '1:269398467482:android:47bab075e9c0bd98c15023',
    messagingSenderId: '269398467482',
    projectId: 'team4-2252f',
    storageBucket: 'team4-2252f.firebasestorage.app',
  );

}